name: Deploy FastAPI App

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to AWS
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ubuntu@18.222.172.175 << 'EOF'
            cd <your-repo-folder>
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF

